### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by VillainXII** [Sworder71/Dashboard.io#2]
i was curious how i could remove the port so i can use just a plain domain, for example, example.com/dashboard

**Comment by Androz2091** [comment]
Hello
To do this, you need Apache (or another http server). Install a process manager, such as `pm2` or `forever`, and launch the dashboard with it on the port of your choice. Modify the dns of your domain name so that it points to your server. Create a specific Apache configuration for this domain name so that it falls on the dashboard (many tutorials are available). And that's good!
